# Generated by Django 2.0 on 2018-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seisnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='network',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
