# Generated by Django 2.0 on 2018-05-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seisnet', '0002_auto_20180529_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='台网描述'),
        ),
    ]
