# Generated by Django 2.0 on 2018-05-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, '地震仪'), (1, '数据采集器'), (2, '供电系统'), (3, '核心配件'), (4, '网络设备'), (5, '其它')], verbose_name='分类'),
        ),
    ]
