# Generated by Django 2.0 on 2018-06-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20180609_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataloggerentity',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='dataloggermodel',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='gpsantenna',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='powersupply',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='sensorentity',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='sensormodel',
            name='polymorphic_ctype',
        ),
    ]
