# Generated by Django 2.0 on 2018-05-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20180525_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='fault_number',
            field=models.PositiveIntegerField(default=0, verbose_name='损坏数'),
        ),
    ]
