# Generated by Django 2.0 on 2018-05-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_fault_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='制造商分类名称')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.ManufacturerCategory', verbose_name='制造商分类'),
        ),
    ]
