# Generated by Django 2.0 on 2018-06-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipment', '0003_auto_20180609_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataloggerentity',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_equipment.dataloggerentity_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='dataloggermodel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_equipment.dataloggermodel_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='gpsantenna',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_equipment.gpsantenna_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_equipment.networkdevice_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_equipment.powersupply_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sensorentity',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_equipment.sensorentity_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sensormodel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_equipment.sensormodel_set+', to='contenttypes.ContentType'),
        ),
    ]
