# Generated by Django 2.0 on 2018-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20180523_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
