# Generated by Django 2.0 on 2018-05-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20180525_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
