# Generated by Django 2.0 on 2018-05-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmententity',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='fault_number',
            field=models.PositiveIntegerField(default=0, verbose_name='故障数'),
        ),
        migrations.AlterField(
            model_name='equipmententity',
            name='getway',
            field=models.PositiveSmallIntegerField(choices=[(0, '自购'), (1, '租赁'), (2, '借用'), (3, '其它')], default=0, verbose_name='获得方式'),
        ),
    ]
