# Generated by Django 2.0 on 2018-05-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20180525_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
