# Generated by Django 2.0 on 2018-05-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20180525_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='category',
            field=models.ManyToManyField(to='equipment.ManufacturerCategory', verbose_name='制造商分类'),
        ),
    ]
