# Generated by Django 2.0 on 2018-05-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=150.0, verbose_name='看护费(元/月)')),
                ('start_pay', models.DateField(verbose_name='支付开始日期(年-月)')),
                ('end_pay', models.DateField(verbose_name='支付截止日期(年-月)')),
                ('pay_date', models.DateField(verbose_name='支付日期')),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('id_card', models.CharField(max_length=64, verbose_name='身份证号')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '在看护'), (2, '曾看护'), (3, '中断')], verbose_name='状态')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('care_payments', models.ManyToManyField(to='basicinfo.CarePayment', verbose_name='看护费')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='台网代码')),
                ('name', models.CharField(max_length=64, verbose_name='台网名称')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('min_longitude', models.FloatField(blank=True, null=True, verbose_name='台网最小经度')),
                ('max_longitude', models.FloatField(blank=True, null=True, verbose_name='台网最大经度')),
                ('min_latitude', models.FloatField(blank=True, null=True, verbose_name='台网最小纬度')),
                ('max_latitude', models.FloatField(blank=True, null=True, verbose_name='台网最大纬度')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '运行'), (1, '测试'), (2, '下线')], default=0, verbose_name='台网状体')),
                ('describe', models.CharField(blank=True, max_length=512, null=True, verbose_name='台网描述')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='号码')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicinfo.Caretaker', verbose_name='所有者')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='台站代码')),
                ('en_name', models.CharField(max_length=64, verbose_name='台站名称(英文)')),
                ('zh_name', models.CharField(max_length=64, verbose_name='台站名称(中文)')),
                ('longitude', models.FloatField(verbose_name='台站经度')),
                ('latitude', models.FloatField(verbose_name='台站纬度')),
                ('altitude', models.FloatField(verbose_name='台站高程')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '运行'), (1, '测试'), (2, '故障'), (3, '下线')], default=0, verbose_name='台站状态')),
                ('describe', models.CharField(blank=True, max_length=512, null=True, verbose_name='台站描述')),
                ('location', models.CharField(max_length=512, verbose_name='位置描述')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('care_payments', models.ManyToManyField(to='basicinfo.CarePayment', verbose_name='看护费')),
                ('caretaker', models.ManyToManyField(to='basicinfo.Caretaker', verbose_name='看护人')),
                ('net', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicinfo.Net', verbose_name='所属台网')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='设备清单', to='basicinfo.Station'),
        ),
    ]
