# Generated by Django 2.0 on 2018-05-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='power_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='电源系统'),
        ),
        migrations.AddField(
            model_name='station',
            name='power_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '在看护'), (2, '曾看护'), (3, '中断')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='net',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '运行'), (1, '测试'), (2, '下线')], default=0, verbose_name='台网状体'),
        ),
        migrations.AlterField(
            model_name='station',
            name='describe',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='台站描述'),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '运行'), (1, '测试'), (2, '故障'), (3, '下线')], default=0, verbose_name='台站状态'),
        ),
    ]
