# Generated by Django 2.0 on 2018-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('basicinfo', '0002_auto_20180522_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='power_id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='power_type',
        ),
        migrations.AddField(
            model_name='station',
            name='power_obj',
            field=models.ManyToManyField(to='equipment.PowerSupply'),
        ),
    ]
