# Generated by Django 2.0 on 2018-05-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0003_auto_20180522_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='power_obj',
            new_name='power_supply',
        ),
    ]
