# Generated by Django 2.0 on 2018-05-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0004_auto_20180522_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='号码')),
            ],
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='station',
            name='power_supply',
        ),
        migrations.AddField(
            model_name='phone',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicinfo.Caretaker', verbose_name='所有者'),
        ),
    ]
