# Generated by Django 2.0 on 2018-05-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_auto_20180523_1451'),
        ('equipment', '0002_auto_20180523_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='设备清单', to='basicinfo.Station'),
        ),
    ]
